# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   selector:
#     app: my-nginx
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort        # เปลี่ยนจาก ClusterIP
  selector:
    app: my-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080     # port ที่เปิดออกมา
